---
- name: start ec2_instance
  hosts: server1
  gather_facts: False
  tasks:
   - pip:
      name: boto
   - name: start ec2_instance-viaAnsible
     ec2_instance:
               instance_ids: 'i-0765c65f25d7f3fbe'
               region: 'us-east-2'
               state: running
               wait: True

